development:
  adapter: postgresql
  encoding: unicode
  database: propertymgt_development
  pool: 5
  username:
  password:


test:
  adapter: postgresql
  encoding: unicode
  database: propertymgt_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: propertymgt_production
  pool: 5
  username:
  password:
